#!/usr/bin/env ruby

def decode_char (char)
  case char
    when	'.-'	
      puts 'A'
    when '-...'
      puts 'B'	
    when	'-.-.'	
      puts 'C'
    when	'-..'
      puts 'D'
    when	'.'	
      puts 'E'
    when	'..-'
      puts 'F'
    when	'--.'	
      puts 'G'
    when	'....'
      puts 'H'
    when	'..'	
      puts 'I'
    when	'.---'
      puts 'J'
    when	'-.-'	
      puts 'K'
    when	'.-..'
      puts 'L'
    when	'--'	
      puts 'M'
    when	'-.'
      puts 'N'
    when	'---'
      puts 'O'
    when	'.--.'
      puts 'P'
    when	'--.-'	
      puts 'Q'
    when	'.-.'
      puts 'R'
    when	'...'	
      'S'
    when	'-'
      puts 'T'
    when	'..-'
      puts 'U'
    when	'...-'
      puts 'V'
    when 	'.--'	
      puts 'W' 
    when	'-..-'
      puts 'X'
    when	'-.--'	
      puts 'Y'
    when	'--..'
      puts 'Z'
    else 
      puts char
  end
end

decode_char '--..'